// This file is autogenerated
#ifndef HAVOK_TYPES_GUARD
#define HAVOK_TYPES_GUARD

#include "havok/havok_support_types.h"

typedef struct hkArray_hkaiStreamingSet__GraphConnection_hkContainerHeapAllocator hkArray_hkaiStreamingSet__GraphConnection_hkContainerHeapAllocator;

typedef struct hkRefPtr_hkaBoneAttachment hkRefPtr_hkaBoneAttachment;

typedef struct hkRefPtr_hkaiStreamingSet hkRefPtr_hkaiStreamingSet;

/* primitive unsigned int*/
typedef unsigned int unsigned_int;

typedef unsigned_int hkUintReal;

typedef enum hkEnum_hkaAnimation__AnimationType_hkInt32 hkEnum_hkaAnimation__AnimationType_hkInt32;

typedef struct hkArray_hkMeshBoneIndexMapping_hkContainerHeapAllocator hkArray_hkMeshBoneIndexMapping_hkContainerHeapAllocator;

typedef enum hkxMaterial__TextureType hkxMaterial__TextureType;

typedef struct hkHashBase_hkHashMapDetail__MapTuple hkHashBase_hkHashMapDetail__MapTuple;

typedef struct hkxVertexAnimation__UsageMap hkxVertexAnimation__UsageMap;

typedef struct hkArray_hkaiNavMesh__Edge_hkContainerHeapAllocator hkArray_hkaiNavMesh__Edge_hkContainerHeapAllocator;

typedef struct hkArray_hkaSkeleton__Partition_hkContainerHeapAllocator hkArray_hkaSkeleton__Partition_hkContainerHeapAllocator;

typedef enum hkEnum_hkaAnimationBinding__BlendHint_hkInt8 hkEnum_hkaAnimationBinding__BlendHint_hkInt8;

typedef struct hkStringPtr hkStringPtr;

typedef struct hkArray_hkaiNavMeshClearanceCache__McpDataInteger_hkContainerHeapAllocator hkArray_hkaiNavMeshClearanceCache__McpDataInteger_hkContainerHeapAllocator;

typedef enum hkxVertexDescription__DataType hkxVertexDescription__DataType;

typedef enum hkEnum_hkxMaterial__Transparency_hkUint8 hkEnum_hkxMaterial__Transparency_hkUint8;

/* primitive unsigned short*/
typedef unsigned short unsigned_short;

typedef unsigned_short hkUint16;

typedef hkUint16 hkFlags_hkaiDirectedGraphExplicitCost__EdgeBits_hkUint16;

typedef struct hkRootLevelContainer hkRootLevelContainer;

typedef struct hkaAnimation hkaAnimation;

typedef struct hkArray_hkxVertexAnimation__UsageMap_hkContainerHeapAllocator hkArray_hkxVertexAnimation__UsageMap_hkContainerHeapAllocator;

typedef struct hkArray_hkaiDirectedGraphExplicitCost__Node_hkContainerHeapAllocator hkArray_hkaiDirectedGraphExplicitCost__Node_hkContainerHeapAllocator;

/* primitive const char**/
typedef enum hkEnum_hkxMaterial__UVMappingAlgorithm_hkUint32 hkEnum_hkxMaterial__UVMappingAlgorithm_hkUint32;

typedef enum hkEnum_hkxVertexDescription__DataType_hkUint16 hkEnum_hkxVertexDescription__DataType_hkUint16;

typedef struct hkPropertyBag hkPropertyBag;

typedef struct hkArray_hkxAttributeGroup_hkContainerHeapAllocator hkArray_hkxAttributeGroup_hkContainerHeapAllocator;

typedef struct hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator;

typedef struct hkxMeshSection hkxMeshSection;

typedef struct hkArray_hkcdStaticTree__Codec3Axis6_hkContainerHeapAllocator hkArray_hkcdStaticTree__Codec3Axis6_hkContainerHeapAllocator;

typedef struct hkArray_hkInt32_hkContainerHeapAllocator hkArray_hkInt32_hkContainerHeapAllocator;

typedef struct hkaAnnotationTrack__Annotation hkaAnnotationTrack__Annotation;

typedef struct hkArray_hkaiNavMeshClearanceCacheSeeding__CacheData_hkContainerHeapAllocator hkArray_hkaiNavMeshClearanceCacheSeeding__CacheData_hkContainerHeapAllocator;

typedef struct hkaiNavMeshClearanceCacheSeeding__CacheDataSet hkaiNavMeshClearanceCacheSeeding__CacheDataSet;

typedef short hkInt16;

typedef struct hkxVertexDescription hkxVertexDescription;

typedef struct hkArray_unsigned_int_hkContainerHeapAllocator hkArray_unsigned_int_hkContainerHeapAllocator;

typedef struct hkxMesh hkxMesh;

typedef struct hkMatrix4f hkMatrix4f;

typedef struct hkTransformf hkTransformf;

typedef hkTransformf hkTransform;

typedef struct hkaDefaultAnimatedReferenceFrame hkaDefaultAnimatedReferenceFrame;

typedef struct hkBool hkBool;

typedef struct hkArray_float_hkContainerHeapAllocator hkArray_float_hkContainerHeapAllocator;

typedef const char* const_char*;

typedef struct hkArray_hkInt16_hkContainerHeapAllocator hkArray_hkInt16_hkContainerHeapAllocator;

typedef struct hkcdStaticTree__Tree_hkcdStaticTree__DynamicStorage hkcdStaticTree__Tree_hkcdStaticTree__DynamicStorage;

typedef hkcdStaticTree__Tree_hkcdStaticTree__DynamicStorage hkcdStaticAabbTree__Impl;

typedef struct hkArray_hkaAnnotationTrack__Annotation_hkContainerHeapAllocator hkArray_hkaAnnotationTrack__Annotation_hkContainerHeapAllocator;

typedef enum hkxMaterial__Transparency hkxMaterial__Transparency;

typedef struct hkRefPtr_hkxMeshSection hkRefPtr_hkxMeshSection;

/* primitive HavokVector4*/
typedef HavokVector4 hkVector4f;

typedef struct hkArray_hkStringPtr_hkContainerHeapAllocator hkArray_hkStringPtr_hkContainerHeapAllocator;

typedef struct hkArray_hkHashMapDetail__MapTuple_hkContainerHeapAllocator hkArray_hkHashMapDetail__MapTuple_hkContainerHeapAllocator;

typedef struct hkRefPtr_hkaAnimatedReferenceFrame hkRefPtr_hkaAnimatedReferenceFrame;

typedef struct hkArray_hkaiStreamingSet__VolumeConnection_hkContainerHeapAllocator hkArray_hkaiStreamingSet__VolumeConnection_hkContainerHeapAllocator;

typedef struct hkRefPtr_hkxVertexBuffer hkRefPtr_hkxVertexBuffer;

typedef struct hkcdStaticTree__DynamicStorage_hkcdStaticTree__Codec3Axis6 hkcdStaticTree__DynamicStorage_hkcdStaticTree__Codec3Axis6;

typedef struct hkArray_hkaiDirectedGraphExplicitCost__Edge_hkContainerHeapAllocator hkArray_hkaiDirectedGraphExplicitCost__Edge_hkContainerHeapAllocator;

typedef struct hkRootLevelContainer__NamedVariant hkRootLevelContainer__NamedVariant;

typedef struct hkaBone hkaBone;

/* primitive unsigned char*/
typedef unsigned char unsigned_char;

typedef unsigned_char hkUint8;

typedef struct hkQsTransformf hkQsTransformf;

typedef hkQsTransformf hkQsTransform;

typedef struct hkaMeshBinding__Mapping hkaMeshBinding__Mapping;

typedef struct hkArray_hkaAnnotationTrack_hkContainerHeapAllocator hkArray_hkaAnnotationTrack_hkContainerHeapAllocator;

typedef struct hkaiNavMeshClearanceCache hkaiNavMeshClearanceCache;

typedef struct hkHashMapDetail__Index hkHashMapDetail__Index;

typedef struct hkQuaternionf hkQuaternionf;

typedef struct hkaiNavMeshClearanceCacheSeeding__CacheData hkaiNavMeshClearanceCacheSeeding__CacheData;

typedef struct hkRefPtr_hkxMesh hkRefPtr_hkxMesh;

typedef struct hkaSkeleton__Partition hkaSkeleton__Partition;

typedef enum hkxVertexDescription__DataUsage hkxVertexDescription__DataUsage;

/* primitive unsigned long long*/
typedef unsigned long long unsigned_long_long;

typedef struct hkcdStaticTree__Codec3Axis6 hkcdStaticTree__Codec3Axis6;

typedef hkRotationImpl_float hkRotationf;

typedef struct hkRefVariant hkRefVariant;

typedef struct hkaiStreamingSet hkaiStreamingSet;

typedef enum hkaAnimation__AnimationType hkaAnimation__AnimationType;

typedef struct hkArray_hkaSkeleton__LocalFrameOnBone_hkContainerHeapAllocator hkArray_hkaSkeleton__LocalFrameOnBone_hkContainerHeapAllocator;

typedef struct hkxAttributeHolder hkxAttributeHolder;

typedef struct hkRefPtr_hkxVertexAnimation hkRefPtr_hkxVertexAnimation;

typedef struct hkArray_hkRootLevelContainer__NamedVariant_hkContainerHeapAllocator hkArray_hkRootLevelContainer__NamedVariant_hkContainerHeapAllocator;

typedef struct hkxVertexBuffer hkxVertexBuffer;

typedef struct hkaAnnotationTrack hkaAnnotationTrack;

typedef struct hkArray_hkxMaterial__TextureStage_hkContainerHeapAllocator hkArray_hkxMaterial__TextureStage_hkContainerHeapAllocator;

typedef struct hkxMaterial hkxMaterial;

typedef struct hkaiStreamingSet__NavMeshConnection hkaiStreamingSet__NavMeshConnection;

typedef struct hkRefPtr_hkaMeshBinding hkRefPtr_hkaMeshBinding;

typedef enum hkEnum_hkxMaterial__TextureType_hkInt32 hkEnum_hkxMaterial__TextureType_hkInt32;

typedef struct hkRefPtr_hkaAnimation hkRefPtr_hkaAnimation;

typedef enum hkaAnimationBinding__BlendHint hkaAnimationBinding__BlendHint;

typedef struct hkArray_hkxVertexDescription__ElementDecl_hkContainerHeapAllocator hkArray_hkxVertexDescription__ElementDecl_hkContainerHeapAllocator;

typedef struct hkaBoneAttachment hkaBoneAttachment;

typedef struct hkaiNavMeshClearanceCache__McpDataInteger hkaiNavMeshClearanceCache__McpDataInteger;

typedef struct hkRefPtr_hkaSkeleton hkRefPtr_hkaSkeleton;

typedef struct hkcdStaticAabbTree hkcdStaticAabbTree;

typedef struct hkReferencedObject hkReferencedObject;

typedef hkReferencedObject hkLocalFrame;

typedef struct hkArray_hkVector4_hkContainerHeapAllocator hkArray_hkVector4_hkContainerHeapAllocator;

typedef struct hkTuple_hkPropertyId_hkReflect__Any_void_void_void_void_void_void hkTuple_hkPropertyId_hkReflect__Any_void_void_void_void_void_void;

typedef hkHashBase_hkHashMapDetail__MapTuple hkHashMap_hkPropertyId_hkReflect__Any;

typedef struct hkRefPtr_hkLocalFrame hkRefPtr_hkLocalFrame;

typedef struct hkaiDirectedGraphExplicitCost__Node hkaiDirectedGraphExplicitCost__Node;

typedef struct hkaSkeleton__LocalFrameOnBone hkaSkeleton__LocalFrameOnBone;

typedef enum hkEnum_hkxIndexBuffer__IndexType_hkInt8 hkEnum_hkxIndexBuffer__IndexType_hkInt8;

typedef struct hkArray_hkxMaterial__Property_hkContainerHeapAllocator hkArray_hkxMaterial__Property_hkContainerHeapAllocator;

typedef struct hkPropertyDesc hkPropertyDesc;

typedef struct hkArray_hkUint8_hkContainerHeapAllocator hkArray_hkUint8_hkContainerHeapAllocator;

typedef struct hkaSkeleton hkaSkeleton;

typedef int hkInt32;

typedef struct hkcdStaticTree__Codec3Axis hkcdStaticTree__Codec3Axis;

typedef struct hkxMesh__UserChannelInfo hkxMesh__UserChannelInfo;

typedef enum hkEnum_hkxVertexDescription__DataUsage_hkUint16 hkEnum_hkxVertexDescription__DataUsage_hkUint16;

typedef struct hkxVertexAnimation hkxVertexAnimation;

typedef struct hkArray_hkaBone_hkContainerHeapAllocator hkArray_hkaBone_hkContainerHeapAllocator;

typedef struct hkaiNavMesh__Edge hkaiNavMesh__Edge;

typedef enum hkEnum_hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_hkInt8 hkEnum_hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_hkInt8;

typedef struct hkxIndexBuffer hkxIndexBuffer;

typedef struct hkaiStreamingSet__GraphConnection hkaiStreamingSet__GraphConnection;

typedef struct hkArray_hkUint16_hkContainerHeapAllocator hkArray_hkUint16_hkContainerHeapAllocator;

typedef struct hkReflect__QualifiedType_hkReflect__Type hkReflect__QualifiedType_hkReflect__Type;

typedef struct hkxAttribute hkxAttribute;

typedef struct hkRefPtr_hkxMaterial hkRefPtr_hkxMaterial;

typedef struct hkxAttributeGroup hkxAttributeGroup;

typedef struct hkaiDirectedGraphExplicitCost hkaiDirectedGraphExplicitCost;

typedef struct hkArray_hkQsTransform_hkContainerHeapAllocator hkArray_hkQsTransform_hkContainerHeapAllocator;

typedef struct hkArray_hkaMeshBinding__Mapping_hkContainerHeapAllocator hkArray_hkaMeshBinding__Mapping_hkContainerHeapAllocator;

typedef enum hkEnum_hkaiAnnotatedStreamingSet__Side_hkUint8 hkEnum_hkaiAnnotatedStreamingSet__Side_hkUint8;

typedef struct hkaAnimationBinding hkaAnimationBinding;

typedef struct hkaiNavMesh hkaiNavMesh;

typedef struct hkaMeshBinding hkaMeshBinding;

typedef unsigned_int hkUint32;

typedef struct hkaiDirectedGraphExplicitCost__Edge hkaiDirectedGraphExplicitCost__Edge;

typedef struct hkMeshBoneIndexMapping hkMeshBoneIndexMapping;

typedef enum hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum;

typedef hkUint32 hkFlags_hkPropertyFlags__Enum_hkUint32;

typedef struct hkaiAnnotatedStreamingSet hkaiAnnotatedStreamingSet;

typedef struct hkRefPtr_hkaAnimationBinding hkRefPtr_hkaAnimationBinding;

typedef unsigned_long_long hkUlong;

typedef enum hkxIndexBuffer__IndexType hkxIndexBuffer__IndexType;

typedef struct hkArray_hkRefPtr_hkContainerHeapAllocator hkArray_hkRefPtr_hkContainerHeapAllocator;

typedef struct hkxMaterial__TextureStage hkxMaterial__TextureStage;

typedef struct hkRefPtr_hkxMesh__UserChannelInfo hkRefPtr_hkxMesh__UserChannelInfo;

typedef enum hkxMaterial__UVMappingAlgorithm hkxMaterial__UVMappingAlgorithm;

typedef struct hkaAnimationContainer hkaAnimationContainer;

typedef struct hkDefaultPropertyBag hkDefaultPropertyBag;

typedef struct hkArray_hkRefVariant_hkContainerHeapAllocator hkArray_hkRefVariant_hkContainerHeapAllocator;

typedef struct hkaSplineCompressedAnimation hkaSplineCompressedAnimation;

typedef struct hkaiNavMesh__Face hkaiNavMesh__Face;

typedef unsigned_int hkaiPackedKey__hkaiIndex_hkaiIndex;

typedef struct hkArray_hkUint32_hkContainerHeapAllocator hkArray_hkUint32_hkContainerHeapAllocator;

typedef struct hkxVertexDescription__ElementDecl hkxVertexDescription__ElementDecl;

typedef struct hkReflect__Any hkReflect__Any;

typedef struct hkArray_hkxAttribute_hkContainerHeapAllocator hkArray_hkxAttribute_hkContainerHeapAllocator;

typedef struct hkaiStreamingSet__VolumeConnection hkaiStreamingSet__VolumeConnection;

typedef hkTuple_hkPropertyId_hkReflect__Any_void_void_void_void_void_void hkHashMapDetail__MapTuple_hkPropertyId_hkReflect__Any;

typedef enum hkaiAnnotatedStreamingSet__Side hkaiAnnotatedStreamingSet__Side;

typedef struct hkRefPtr_hkxIndexBuffer hkRefPtr_hkxIndexBuffer;

typedef struct hkArray_hkReal_hkContainerHeapAllocator hkArray_hkReal_hkContainerHeapAllocator;

typedef struct hkPropertyId hkPropertyId;

typedef struct hkAabb hkAabb;

typedef struct hkxVertexBuffer__VertexData hkxVertexBuffer__VertexData;

typedef hkMatrix4f hkMatrix4;

typedef struct hkaAnimatedReferenceFrame hkaAnimatedReferenceFrame;

typedef struct hkRefPtr_hkaiNavMeshClearanceCache hkRefPtr_hkaiNavMeshClearanceCache;

typedef hkVector4f hkVector4;

typedef signed_char hkInt8;

typedef hkInt32 hkaiIndex_hkInt32;

typedef struct hkPtrAndInt_hkPropertyDesc_unsigned_int_1 hkPtrAndInt_hkPropertyDesc_unsigned_int_1;

typedef hkUint8 hkFlags_hkaiNavMesh__EdgeFlagBits_hkUint8;

typedef struct hkArray_hkaiNavMesh__Face_hkContainerHeapAllocator hkArray_hkaiNavMesh__Face_hkContainerHeapAllocator;

typedef struct hkArray_hkAabb_hkContainerHeapAllocator hkArray_hkAabb_hkContainerHeapAllocator;

typedef struct hkaiFaceEdgeIndexPair hkaiFaceEdgeIndexPair;

typedef struct hkArray_hkTransform_hkContainerHeapAllocator hkArray_hkTransform_hkContainerHeapAllocator;

typedef struct hkArray_hkaiStreamingSet__NavMeshConnection_hkContainerHeapAllocator hkArray_hkaiStreamingSet__NavMeshConnection_hkContainerHeapAllocator;

typedef struct hkRefPtr_hkaiNavMeshClearanceCacheSeeding__CacheDataSet hkRefPtr_hkaiNavMeshClearanceCacheSeeding__CacheDataSet;

typedef struct hkHalf16 hkHalf16;

typedef struct hkxMaterial__Property hkxMaterial__Property;

typedef float hkReal;

#define hkArray_hkaiStreamingSet__GraphConnection_hkContainerHeapAllocator_HASH 0x01BBAB95
typedef struct hkArray_hkaiStreamingSet__GraphConnection_hkContainerHeapAllocator {
    hkaiStreamingSet__GraphConnection* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiStreamingSet__GraphConnection_hkContainerHeapAllocator;

#define hkRefPtr_hkaBoneAttachment_HASH 0x02D6E435
typedef struct hkRefPtr_hkaBoneAttachment {
    hkaBoneAttachment* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaBoneAttachment;

#define hkRefPtr_hkaiStreamingSet_HASH 0x031086EE
typedef struct hkRefPtr_hkaiStreamingSet {
    hkaiStreamingSet* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaiStreamingSet;

/* primitive unsigned int*/
#define hkEnum_hkaAnimation__AnimationType_hkInt32_HASH 0x053FBA35
typedef enum hkEnum_hkaAnimation__AnimationType_hkInt32 { // size: 0
} hkEnum_hkaAnimation__AnimationType_hkInt32;

#define hkArray_hkMeshBoneIndexMapping_hkContainerHeapAllocator_HASH 0x069095C1
typedef struct hkArray_hkMeshBoneIndexMapping_hkContainerHeapAllocator {
    hkMeshBoneIndexMapping* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkMeshBoneIndexMapping_hkContainerHeapAllocator;

#define hkxMaterial__TextureType_HASH 0x06A4E879
typedef enum hkxMaterial__TextureType { // size: 4
} hkxMaterial__TextureType;

#define hkArray_hkHashMapDetail__MapTuple_hkContainerHeapAllocator_HASH 0x47FA5A47
typedef struct hkArray_hkHashMapDetail__MapTuple_hkContainerHeapAllocator {
    hkHashMapDetail__MapTuple* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkHashMapDetail__MapTuple_hkContainerHeapAllocator;

#define hkHashMapDetail__Index_HASH 0x59433997
typedef struct hkHashMapDetail__Index {
    void* entries; // offset: 0, flags: 32, size: 8
    int hashMod; // offset: 8, flags: 32, size: 4
} hkHashMapDetail__Index;

#define hkHashBase_hkHashMapDetail__MapTuple_HASH 0x06B8FA4D
typedef struct hkHashBase_hkHashMapDetail__MapTuple {
    hkArray_hkHashMapDetail__MapTuple_hkContainerHeapAllocator items; // offset: 0, flags: 34, size: 16
    hkHashMapDetail__Index index; // offset: 16, flags: 35, size: 16
} hkHashBase_hkHashMapDetail__MapTuple;

#define hkEnum_hkxVertexDescription__DataUsage_hkUint16_HASH 0xA90917C9
typedef enum hkEnum_hkxVertexDescription__DataUsage_hkUint16 { // size: 0
} hkEnum_hkxVertexDescription__DataUsage_hkUint16;

#define hkxVertexAnimation__UsageMap_HASH 0x077BE577
typedef struct hkxVertexAnimation__UsageMap {
    hkEnum_hkxVertexDescription__DataUsage_hkUint16 use; // offset: 0, flags: 32, size: 0
    hkUint8 useIndexOrig; // offset: 2, flags: 32, size: 0
    hkUint8 useIndexLocal; // offset: 3, flags: 32, size: 0
} hkxVertexAnimation__UsageMap;

#define hkArray_hkaiNavMesh__Edge_hkContainerHeapAllocator_HASH 0x09F2C1A5
typedef struct hkArray_hkaiNavMesh__Edge_hkContainerHeapAllocator {
    hkaiNavMesh__Edge* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiNavMesh__Edge_hkContainerHeapAllocator;

#define hkArray_hkaSkeleton__Partition_hkContainerHeapAllocator_HASH 0x0A08F869
typedef struct hkArray_hkaSkeleton__Partition_hkContainerHeapAllocator {
    hkaSkeleton__Partition* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaSkeleton__Partition_hkContainerHeapAllocator;

#define hkEnum_hkaAnimationBinding__BlendHint_hkInt8_HASH 0x0AA8F38E
typedef enum hkEnum_hkaAnimationBinding__BlendHint_hkInt8 { // size: 0
} hkEnum_hkaAnimationBinding__BlendHint_hkInt8;

#define hkStringPtr_HASH 0x0BBFA3EE
typedef struct hkStringPtr {
    const_char* stringAndFlag; // offset: 0, flags: 36, size: 8
} hkStringPtr;

#define hkArray_hkaiNavMeshClearanceCache__McpDataInteger_hkContainerHeapAllocator_HASH 0x0CF8BD30
typedef struct hkArray_hkaiNavMeshClearanceCache__McpDataInteger_hkContainerHeapAllocator {
    hkaiNavMeshClearanceCache__McpDataInteger* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiNavMeshClearanceCache__McpDataInteger_hkContainerHeapAllocator;

#define hkxVertexDescription__DataType_HASH 0x0D908C11
typedef enum hkxVertexDescription__DataType { // size: 4
} hkxVertexDescription__DataType;

#define hkEnum_hkxMaterial__Transparency_hkUint8_HASH 0x0FACB3A9
typedef enum hkEnum_hkxMaterial__Transparency_hkUint8 { // size: 0
} hkEnum_hkxMaterial__Transparency_hkUint8;

#define hkArray_hkRootLevelContainer__NamedVariant_hkContainerHeapAllocator_HASH 0x77278F14
typedef struct hkArray_hkRootLevelContainer__NamedVariant_hkContainerHeapAllocator {
    hkRootLevelContainer__NamedVariant* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkRootLevelContainer__NamedVariant_hkContainerHeapAllocator;

#define hkRootLevelContainer_HASH 0x10BB2BE3
typedef struct hkRootLevelContainer {
    hkArray_hkRootLevelContainer__NamedVariant_hkContainerHeapAllocator namedVariants; // offset: 0, flags: 32, size: 16
} hkRootLevelContainer;

#define hkRefPtr_hkaAnimatedReferenceFrame_HASH 0x4819EB67
typedef struct hkRefPtr_hkaAnimatedReferenceFrame {
    hkaAnimatedReferenceFrame* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaAnimatedReferenceFrame;

#define hkArray_hkaAnnotationTrack_hkContainerHeapAllocator_HASH 0x584AF649
typedef struct hkArray_hkaAnnotationTrack_hkContainerHeapAllocator {
    hkaAnnotationTrack* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaAnnotationTrack_hkContainerHeapAllocator;

#define hkPropertyBag_HASH 0x1C378877
typedef struct hkPropertyBag {
    hkDefaultPropertyBag* bag; // offset: 0, flags: 35, size: 8
} hkPropertyBag;

#define hkReferencedObject_HASH 0xB8672297
typedef struct hkReferencedObject {
    struct hkBaseObject;
    hkPropertyBag propertyBag; // offset: 8, flags: 36, size: 8
    hkUint16 memSizeAndFlags; // offset: 16, flags: 37, size: 0
    hkUint16 refCount; // offset: 18, flags: 37, size: 0
} hkReferencedObject;

#define hkaAnimation_HASH 0x12F6E0DF
typedef struct hkaAnimation {
    struct hkReferencedObject;
    hkEnum_hkaAnimation__AnimationType_hkInt32 type; // offset: 24, flags: 34, size: 0
    hkReal duration; // offset: 28, flags: 32, size: 0
    int numberOfTransformTracks; // offset: 32, flags: 32, size: 4
    int numberOfFloatTracks; // offset: 36, flags: 32, size: 4
    hkRefPtr_hkaAnimatedReferenceFrame extractedMotion; // offset: 40, flags: 34, size: 8
    hkArray_hkaAnnotationTrack_hkContainerHeapAllocator annotationTracks; // offset: 48, flags: 32, size: 16
} hkaAnimation;

#define hkArray_hkxVertexAnimation__UsageMap_hkContainerHeapAllocator_HASH 0x151F3C24
typedef struct hkArray_hkxVertexAnimation__UsageMap_hkContainerHeapAllocator {
    hkxVertexAnimation__UsageMap* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkxVertexAnimation__UsageMap_hkContainerHeapAllocator;

#define hkArray_hkaiDirectedGraphExplicitCost__Node_hkContainerHeapAllocator_HASH 0x1551013D
typedef struct hkArray_hkaiDirectedGraphExplicitCost__Node_hkContainerHeapAllocator {
    hkaiDirectedGraphExplicitCost__Node* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiDirectedGraphExplicitCost__Node_hkContainerHeapAllocator;

/* primitive const char**/
#define hkEnum_hkxMaterial__UVMappingAlgorithm_hkUint32_HASH 0x178C22AA
typedef enum hkEnum_hkxMaterial__UVMappingAlgorithm_hkUint32 { // size: 0
} hkEnum_hkxMaterial__UVMappingAlgorithm_hkUint32;

#define hkEnum_hkxVertexDescription__DataType_hkUint16_HASH 0x181904EF
typedef enum hkEnum_hkxVertexDescription__DataType_hkUint16 { // size: 0
} hkEnum_hkxVertexDescription__DataType_hkUint16;

#define hkArray_hkxAttributeGroup_hkContainerHeapAllocator_HASH 0x21D0B990
typedef struct hkArray_hkxAttributeGroup_hkContainerHeapAllocator {
    hkxAttributeGroup* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkxAttributeGroup_hkContainerHeapAllocator;

#define hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator_HASH 0x2348FFB8
typedef struct hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator {
    hkaiAnnotatedStreamingSet* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator;

#define hkRefPtr_hkxVertexBuffer_HASH 0x4B9CD60F
typedef struct hkRefPtr_hkxVertexBuffer {
    hkxVertexBuffer* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxVertexBuffer;

#define hkArray_hkRefPtr_hkContainerHeapAllocator_HASH 0xCACE7A49
typedef struct hkArray_hkRefPtr_hkContainerHeapAllocator {
    hkRefPtr* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkRefPtr_hkContainerHeapAllocator;

#define hkRefPtr_hkxMaterial_HASH 0xB76C984D
typedef struct hkRefPtr_hkxMaterial {
    hkxMaterial* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxMaterial;

#define hkArray_hkRefVariant_hkContainerHeapAllocator_HASH 0xD4279FE6
typedef struct hkArray_hkRefVariant_hkContainerHeapAllocator {
    hkRefVariant* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkRefVariant_hkContainerHeapAllocator;

#define hkArray_float_hkContainerHeapAllocator_HASH 0x392D925B
typedef struct hkArray_float_hkContainerHeapAllocator {
    float* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_float_hkContainerHeapAllocator;

#define hkxMeshSection_HASH 0x23DAF45B
typedef struct hkxMeshSection {
    struct hkReferencedObject;
    hkRefPtr_hkxVertexBuffer vertexBuffer; // offset: 24, flags: 32, size: 8
    hkArray_hkRefPtr_hkContainerHeapAllocator indexBuffers; // offset: 32, flags: 32, size: 16
    hkRefPtr_hkxMaterial material; // offset: 48, flags: 32, size: 8
    hkArray_hkRefVariant_hkContainerHeapAllocator userChannels; // offset: 56, flags: 32, size: 16
    hkArray_hkRefPtr_hkContainerHeapAllocator vertexAnimations; // offset: 72, flags: 32, size: 16
    hkArray_float_hkContainerHeapAllocator linearKeyFrameHints; // offset: 88, flags: 32, size: 16
    hkArray_hkMeshBoneIndexMapping_hkContainerHeapAllocator boneMatrixMap; // offset: 104, flags: 32, size: 16
} hkxMeshSection;

#define hkArray_hkcdStaticTree__Codec3Axis6_hkContainerHeapAllocator_HASH 0x24EED82B
typedef struct hkArray_hkcdStaticTree__Codec3Axis6_hkContainerHeapAllocator {
    hkcdStaticTree__Codec3Axis6* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkcdStaticTree__Codec3Axis6_hkContainerHeapAllocator;

#define hkArray_hkInt32_hkContainerHeapAllocator_HASH 0x25649495
typedef struct hkArray_hkInt32_hkContainerHeapAllocator {
    hkInt32* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkInt32_hkContainerHeapAllocator;

#define hkaAnnotationTrack__Annotation_HASH 0x26EDD7EA
typedef struct hkaAnnotationTrack__Annotation {
    hkReal time; // offset: 0, flags: 32, size: 0
    hkStringPtr text; // offset: 8, flags: 32, size: 8
} hkaAnnotationTrack__Annotation;

#define hkArray_hkaiNavMeshClearanceCacheSeeding__CacheData_hkContainerHeapAllocator_HASH 0x277E908F
typedef struct hkArray_hkaiNavMeshClearanceCacheSeeding__CacheData_hkContainerHeapAllocator {
    hkaiNavMeshClearanceCacheSeeding__CacheData* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiNavMeshClearanceCacheSeeding__CacheData_hkContainerHeapAllocator;

#define hkaiNavMeshClearanceCacheSeeding__CacheDataSet_HASH 0x2792877F
typedef struct hkaiNavMeshClearanceCacheSeeding__CacheDataSet {
    struct hkReferencedObject;
    hkArray_hkaiNavMeshClearanceCacheSeeding__CacheData_hkContainerHeapAllocator cacheDatas; // offset: 24, flags: 36, size: 16
} hkaiNavMeshClearanceCacheSeeding__CacheDataSet;

#define hkArray_hkxVertexDescription__ElementDecl_hkContainerHeapAllocator_HASH 0x889FE6AB
typedef struct hkArray_hkxVertexDescription__ElementDecl_hkContainerHeapAllocator {
    hkxVertexDescription__ElementDecl* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkxVertexDescription__ElementDecl_hkContainerHeapAllocator;

#define hkxVertexDescription_HASH 0x2E4BFD1B
typedef struct hkxVertexDescription {
    hkArray_hkxVertexDescription__ElementDecl_hkContainerHeapAllocator decls; // offset: 0, flags: 32, size: 16
} hkxVertexDescription;

#define hkArray_unsigned_int_hkContainerHeapAllocator_HASH 0x2F923C9D
typedef struct hkArray_unsigned_int_hkContainerHeapAllocator {
    unsigned_int* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_unsigned_int_hkContainerHeapAllocator;

#define hkxMesh_HASH 0x32A04237
typedef struct hkxMesh {
    struct hkReferencedObject;
    hkArray_hkRefPtr_hkContainerHeapAllocator sections; // offset: 24, flags: 32, size: 16
    hkArray_hkRefPtr_hkContainerHeapAllocator userChannelInfos; // offset: 40, flags: 32, size: 16
} hkxMesh;

#define hkMatrix4f_HASH 0x34D88D47
typedef struct hkMatrix4f {
    hkVector4f col0; // offset: 0, flags: 34, size: 16
    hkVector4f col1; // offset: 16, flags: 34, size: 16
    hkVector4f col2; // offset: 32, flags: 34, size: 16
    hkVector4f col3; // offset: 48, flags: 34, size: 16
} hkMatrix4f;

#define hkArray_hkVector4_hkContainerHeapAllocator_HASH 0x8EC74C73
typedef struct hkArray_hkVector4_hkContainerHeapAllocator {
    hkVector4* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkVector4_hkContainerHeapAllocator;

#define hkEnum_hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_hkInt8_HASH 0xB473E93C
typedef enum hkEnum_hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_hkInt8 { // size: 0
} hkEnum_hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_hkInt8;

#define hkaAnimatedReferenceFrame_HASH 0xEE25AB30
typedef struct hkaAnimatedReferenceFrame {
    struct hkReferencedObject;
    hkEnum_hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_hkInt8 frameType; // offset: 24, flags: 33, size: 0
} hkaAnimatedReferenceFrame;

#define hkaDefaultAnimatedReferenceFrame_HASH 0x37DD60F5
typedef struct hkaDefaultAnimatedReferenceFrame {
    struct hkaAnimatedReferenceFrame;
    hkVector4 up; // offset: 32, flags: 32, size: 0
    hkVector4 forward; // offset: 48, flags: 32, size: 0
    hkReal duration; // offset: 64, flags: 32, size: 0
    hkArray_hkVector4_hkContainerHeapAllocator referenceFrameSamples; // offset: 72, flags: 32, size: 16
} hkaDefaultAnimatedReferenceFrame;

#define hkBool_HASH 0x3807AECD
typedef struct hkBool {
    char bool; // offset: 0, flags: 36, size: 1
} hkBool;

#define hkArray_hkInt16_hkContainerHeapAllocator_HASH 0x3C434B9F
typedef struct hkArray_hkInt16_hkContainerHeapAllocator {
    hkInt16* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkInt16_hkContainerHeapAllocator;

#define hkArray_hkaAnnotationTrack__Annotation_hkContainerHeapAllocator_HASH 0x3D1C400F
typedef struct hkArray_hkaAnnotationTrack__Annotation_hkContainerHeapAllocator {
    hkaAnnotationTrack__Annotation* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaAnnotationTrack__Annotation_hkContainerHeapAllocator;

#define hkxMaterial__Transparency_HASH 0x3E1B5332
typedef enum hkxMaterial__Transparency { // size: 4
} hkxMaterial__Transparency;

#define hkRefPtr_hkxMeshSection_HASH 0x3F934ABE
typedef struct hkRefPtr_hkxMeshSection {
    hkxMeshSection* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxMeshSection;

#define hkArray_hkStringPtr_hkContainerHeapAllocator_HASH 0x464108B2
typedef struct hkArray_hkStringPtr_hkContainerHeapAllocator {
    hkStringPtr* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkStringPtr_hkContainerHeapAllocator;

#define hkArray_hkaiStreamingSet__VolumeConnection_hkContainerHeapAllocator_HASH 0x49327487
typedef struct hkArray_hkaiStreamingSet__VolumeConnection_hkContainerHeapAllocator {
    hkaiStreamingSet__VolumeConnection* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiStreamingSet__VolumeConnection_hkContainerHeapAllocator;

#define hkcdStaticTree__DynamicStorage_hkcdStaticTree__Codec3Axis6_HASH 0x4C0B30F3
typedef struct hkcdStaticTree__DynamicStorage_hkcdStaticTree__Codec3Axis6 {
    hkArray_hkcdStaticTree__Codec3Axis6_hkContainerHeapAllocator nodes; // offset: 0, flags: 32, size: 16
} hkcdStaticTree__DynamicStorage_hkcdStaticTree__Codec3Axis6;

#define hkArray_hkaiDirectedGraphExplicitCost__Edge_hkContainerHeapAllocator_HASH 0x4E4602CB
typedef struct hkArray_hkaiDirectedGraphExplicitCost__Edge_hkContainerHeapAllocator {
    hkaiDirectedGraphExplicitCost__Edge* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiDirectedGraphExplicitCost__Edge_hkContainerHeapAllocator;

#define hkRefVariant_HASH 0x6AD557D8
typedef struct hkRefVariant {
    hkReferencedObject* ptr; // offset: 0, flags: 36, size: 8
} hkRefVariant;

#define hkRootLevelContainer__NamedVariant_HASH 0x4FD6CAA0
typedef struct hkRootLevelContainer__NamedVariant {
    hkStringPtr name; // offset: 0, flags: 36, size: 8
    hkStringPtr className; // offset: 8, flags: 36, size: 8
    hkRefVariant variant; // offset: 16, flags: 36, size: 8
} hkRootLevelContainer__NamedVariant;

#define hkaBone_HASH 0x5398B77C
typedef struct hkaBone {
    hkStringPtr name; // offset: 0, flags: 32, size: 8
    hkBool lockTranslation; // offset: 8, flags: 32, size: 1
} hkaBone;

#define hkaMeshBinding__Mapping_HASH 0x57A6B4F7
typedef struct hkaMeshBinding__Mapping {
    hkArray_hkInt16_hkContainerHeapAllocator mapping; // offset: 0, flags: 32, size: 16
} hkaMeshBinding__Mapping;

#define hkArray_hkUint32_hkContainerHeapAllocator_HASH 0xDB8A31A3
typedef struct hkArray_hkUint32_hkContainerHeapAllocator {
    hkUint32* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkUint32_hkContainerHeapAllocator;

#define hkArray_hkUint8_hkContainerHeapAllocator_HASH 0x9CD19D4F
typedef struct hkArray_hkUint8_hkContainerHeapAllocator {
    hkUint8* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkUint8_hkContainerHeapAllocator;

#define hkaiNavMeshClearanceCache_HASH 0x58BDBAE0
typedef struct hkaiNavMeshClearanceCache {
    struct hkReferencedObject;
    hkReal clearanceCeiling; // offset: 24, flags: 34, size: 0
    hkReal clearanceIntToRealMultiplier; // offset: 28, flags: 34, size: 0
    hkReal clearanceRealToIntMultiplier; // offset: 32, flags: 34, size: 0
    hkArray_hkUint32_hkContainerHeapAllocator faceOffsets; // offset: 40, flags: 34, size: 16
    hkArray_hkUint8_hkContainerHeapAllocator edgePairClearances; // offset: 56, flags: 34, size: 16
    int unusedEdgePairElements; // offset: 72, flags: 34, size: 4
    hkArray_hkaiNavMeshClearanceCache__McpDataInteger_hkContainerHeapAllocator mcpData; // offset: 80, flags: 34, size: 16
    hkArray_hkUint8_hkContainerHeapAllocator vertexClearances; // offset: 96, flags: 34, size: 16
    int uncalculatedFacesLowerBound; // offset: 112, flags: 34, size: 4
} hkaiNavMeshClearanceCache;

#define hkQuaternionf_HASH 0x5C166977
typedef struct hkQuaternionf {
    hkVector4f vec; // offset: 0, flags: 32, size: 16
} hkQuaternionf;

#define hkRefPtr_hkaiNavMeshClearanceCache_HASH 0xEE98BEBB
typedef struct hkRefPtr_hkaiNavMeshClearanceCache {
    hkaiNavMeshClearanceCache* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaiNavMeshClearanceCache;

#define hkaiNavMeshClearanceCacheSeeding__CacheData_HASH 0x5CC07902
typedef struct hkaiNavMeshClearanceCacheSeeding__CacheData {
    hkUlong id; // offset: 0, flags: 32, size: 0
    hkUint32 info; // offset: 8, flags: 32, size: 0
    hkUint32 infoMask; // offset: 12, flags: 32, size: 0
    hkRefPtr_hkaiNavMeshClearanceCache initialCache; // offset: 16, flags: 32, size: 8
} hkaiNavMeshClearanceCacheSeeding__CacheData;

#define hkRefPtr_hkxMesh_HASH 0x5F5046E7
typedef struct hkRefPtr_hkxMesh {
    hkxMesh* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxMesh;

#define hkaSkeleton__Partition_HASH 0x607C1A8E
typedef struct hkaSkeleton__Partition {
    hkStringPtr name; // offset: 0, flags: 32, size: 8
    hkInt16 startBoneIndex; // offset: 8, flags: 32, size: 0
    hkInt16 numBones; // offset: 10, flags: 32, size: 0
} hkaSkeleton__Partition;

#define hkxVertexDescription__DataUsage_HASH 0x66AC12B4
typedef enum hkxVertexDescription__DataUsage { // size: 4
} hkxVertexDescription__DataUsage;

#define hkcdStaticTree__Codec3Axis_HASH 0xA3ECD4D2
typedef struct hkcdStaticTree__Codec3Axis {
    hkUint8 xyz[3]; // offset: 0, flags: 32, size: 3
} hkcdStaticTree__Codec3Axis;

#define hkcdStaticTree__Codec3Axis6_HASH 0x694D0BD0
typedef struct hkcdStaticTree__Codec3Axis6 {
    struct hkcdStaticTree__Codec3Axis;
    hkUint8 hiData; // offset: 3, flags: 32, size: 0
    hkUint16 loData; // offset: 4, flags: 32, size: 0
} hkcdStaticTree__Codec3Axis6;

#define hkArray_hkaiStreamingSet__NavMeshConnection_hkContainerHeapAllocator_HASH 0xFC14EC6A
typedef struct hkArray_hkaiStreamingSet__NavMeshConnection_hkContainerHeapAllocator {
    hkaiStreamingSet__NavMeshConnection* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiStreamingSet__NavMeshConnection_hkContainerHeapAllocator;

#define hkArray_hkAabb_hkContainerHeapAllocator_HASH 0xF892E20A
typedef struct hkArray_hkAabb_hkContainerHeapAllocator {
    hkAabb* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkAabb_hkContainerHeapAllocator;

#define hkaiStreamingSet_HASH 0x6D03E81A
typedef struct hkaiStreamingSet {
    struct hkReferencedObject;
    hkUint32 aSectionUid; // offset: 24, flags: 32, size: 0
    hkUint32 bSectionUid; // offset: 28, flags: 32, size: 0
    hkArray_hkaiStreamingSet__NavMeshConnection_hkContainerHeapAllocator meshConnections; // offset: 32, flags: 32, size: 16
    hkArray_hkaiStreamingSet__GraphConnection_hkContainerHeapAllocator graphConnections; // offset: 48, flags: 32, size: 16
    hkArray_hkaiStreamingSet__VolumeConnection_hkContainerHeapAllocator volumeConnections; // offset: 64, flags: 32, size: 16
    hkArray_hkAabb_hkContainerHeapAllocator aConnectionAabbs; // offset: 80, flags: 32, size: 16
    hkArray_hkAabb_hkContainerHeapAllocator bConnectionAabbs; // offset: 96, flags: 32, size: 16
} hkaiStreamingSet;

#define hkaAnimation__AnimationType_HASH 0x6D3B1C8C
typedef enum hkaAnimation__AnimationType { // size: 4
} hkaAnimation__AnimationType;

#define hkArray_hkaSkeleton__LocalFrameOnBone_hkContainerHeapAllocator_HASH 0x6D5C2237
typedef struct hkArray_hkaSkeleton__LocalFrameOnBone_hkContainerHeapAllocator {
    hkaSkeleton__LocalFrameOnBone* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaSkeleton__LocalFrameOnBone_hkContainerHeapAllocator;

#define hkxAttributeHolder_HASH 0x6D5E84D4
typedef struct hkxAttributeHolder {
    struct hkReferencedObject;
    hkArray_hkxAttributeGroup_hkContainerHeapAllocator attributeGroups; // offset: 24, flags: 32, size: 16
} hkxAttributeHolder;

#define hkRefPtr_hkxVertexAnimation_HASH 0x7130CD56
typedef struct hkRefPtr_hkxVertexAnimation {
    hkxVertexAnimation* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxVertexAnimation;

/* primitive unsigned short*/
#define hkArray_hkUint16_hkContainerHeapAllocator_HASH 0xB4ADD99B
typedef struct hkArray_hkUint16_hkContainerHeapAllocator {
    hkUint16* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkUint16_hkContainerHeapAllocator;

#define hkxVertexBuffer__VertexData_HASH 0xEB674BA1
typedef struct hkxVertexBuffer__VertexData {
    hkArray_unsigned_int_hkContainerHeapAllocator vectorData; // offset: 0, flags: 32, size: 16
    hkArray_unsigned_int_hkContainerHeapAllocator floatData; // offset: 16, flags: 32, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator uint32Data; // offset: 32, flags: 32, size: 16
    hkArray_hkUint16_hkContainerHeapAllocator uint16Data; // offset: 48, flags: 32, size: 16
    hkArray_hkUint8_hkContainerHeapAllocator uint8Data; // offset: 64, flags: 32, size: 16
    hkUint32 numVerts; // offset: 80, flags: 32, size: 0
    hkUint32 vectorStride; // offset: 84, flags: 32, size: 0
    hkUint32 floatStride; // offset: 88, flags: 32, size: 0
    hkUint32 uint32Stride; // offset: 92, flags: 32, size: 0
    hkUint32 uint16Stride; // offset: 96, flags: 32, size: 0
    hkUint32 uint8Stride; // offset: 100, flags: 32, size: 0
} hkxVertexBuffer__VertexData;

#define hkxVertexBuffer_HASH 0x7854546B
typedef struct hkxVertexBuffer {
    struct hkReferencedObject;
    hkxVertexBuffer__VertexData data; // offset: 24, flags: 34, size: 104
    hkxVertexDescription desc; // offset: 128, flags: 34, size: 16
} hkxVertexBuffer;

#define hkaAnnotationTrack_HASH 0x787C0794
typedef struct hkaAnnotationTrack {
    hkStringPtr trackName; // offset: 0, flags: 32, size: 8
    hkArray_hkaAnnotationTrack__Annotation_hkContainerHeapAllocator annotations; // offset: 8, flags: 32, size: 16
} hkaAnnotationTrack;

#define hkArray_hkxMaterial__TextureStage_hkContainerHeapAllocator_HASH 0x79253DEC
typedef struct hkArray_hkxMaterial__TextureStage_hkContainerHeapAllocator {
    hkxMaterial__TextureStage* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkxMaterial__TextureStage_hkContainerHeapAllocator;

#define hkArray_hkxMaterial__Property_hkContainerHeapAllocator_HASH 0x9AF3A508
typedef struct hkArray_hkxMaterial__Property_hkContainerHeapAllocator {
    hkxMaterial__Property* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkxMaterial__Property_hkContainerHeapAllocator;

#define hkxMaterial_HASH 0x7A06A251
typedef struct hkxMaterial {
    struct hkxAttributeHolder;
    hkStringPtr name; // offset: 40, flags: 32, size: 8
    hkArray_hkxMaterial__TextureStage_hkContainerHeapAllocator stages; // offset: 48, flags: 32, size: 16
    hkVector4 diffuseColor; // offset: 64, flags: 32, size: 0
    hkVector4 ambientColor; // offset: 80, flags: 32, size: 0
    hkVector4 specularColor; // offset: 96, flags: 32, size: 0
    hkVector4 emissiveColor; // offset: 112, flags: 32, size: 0
    hkArray_hkRefPtr_hkContainerHeapAllocator subMaterials; // offset: 128, flags: 32, size: 16
    hkRefVariant extraData; // offset: 144, flags: 32, size: 8
    hkReal uvMapScale[2]; // offset: 152, flags: 32, size: 8
    hkReal uvMapOffset[2]; // offset: 160, flags: 32, size: 8
    hkReal uvMapRotation; // offset: 168, flags: 32, size: 0
    hkEnum_hkxMaterial__UVMappingAlgorithm_hkUint32 uvMapAlgorithm; // offset: 172, flags: 32, size: 0
    hkReal specularMultiplier; // offset: 176, flags: 32, size: 0
    hkReal specularExponent; // offset: 180, flags: 32, size: 0
    hkEnum_hkxMaterial__Transparency_hkUint8 transparency; // offset: 184, flags: 32, size: 0
    hkUlong userData; // offset: 192, flags: 32, size: 0
    hkArray_hkxMaterial__Property_hkContainerHeapAllocator properties; // offset: 200, flags: 34, size: 16
} hkxMaterial;

#define hkaiFaceEdgeIndexPair_HASH 0xF926982B
typedef struct hkaiFaceEdgeIndexPair {
    hkaiIndex_hkInt32 faceIndex; // offset: 0, flags: 32, size: 0
    hkaiIndex_hkInt32 edgeIndex; // offset: 4, flags: 32, size: 0
} hkaiFaceEdgeIndexPair;

#define hkaiStreamingSet__NavMeshConnection_HASH 0x7B2CAFC4
typedef struct hkaiStreamingSet__NavMeshConnection {
    hkaiFaceEdgeIndexPair aFaceEdgeIndex; // offset: 0, flags: 32, size: 8
    hkaiFaceEdgeIndexPair bFaceEdgeIndex; // offset: 8, flags: 32, size: 8
} hkaiStreamingSet__NavMeshConnection;

#define hkAabb_HASH 0xE971568A
typedef struct hkAabb {
    hkVector4 min; // offset: 0, flags: 32, size: 0
    hkVector4 max; // offset: 16, flags: 32, size: 0
} hkAabb;

#define hkcdStaticTree__Tree_hkcdStaticTree__DynamicStorage_HASH 0x836B2321
typedef struct hkcdStaticTree__Tree_hkcdStaticTree__DynamicStorage {
    struct hkcdStaticTree__DynamicStorage_hkcdStaticTree__Codec3Axis6;
    hkAabb domain; // offset: 16, flags: 32, size: 32
} hkcdStaticTree__Tree_hkcdStaticTree__DynamicStorage;

#define hkRefPtr_hkaMeshBinding_HASH 0x85245145
typedef struct hkRefPtr_hkaMeshBinding {
    hkaMeshBinding* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaMeshBinding;

#define hkEnum_hkxMaterial__TextureType_hkInt32_HASH 0x864DDBF9
typedef enum hkEnum_hkxMaterial__TextureType_hkInt32 { // size: 0
} hkEnum_hkxMaterial__TextureType_hkInt32;

#define hkRefPtr_hkaAnimation_HASH 0x87C5AA69
typedef struct hkRefPtr_hkaAnimation {
    hkaAnimation* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaAnimation;

#define hkaAnimationBinding__BlendHint_HASH 0x88450055
typedef enum hkaAnimationBinding__BlendHint { // size: 4
} hkaAnimationBinding__BlendHint;

#define hkaBoneAttachment_HASH 0x89368EF6
typedef struct hkaBoneAttachment {
    struct hkReferencedObject;
    hkStringPtr originalSkeletonName; // offset: 24, flags: 32, size: 8
    hkMatrix4 boneFromAttachment; // offset: 32, flags: 32, size: 0
    hkRefVariant attachment; // offset: 96, flags: 32, size: 8
    hkStringPtr name; // offset: 104, flags: 32, size: 8
    hkInt16 boneIndex; // offset: 112, flags: 32, size: 0
} hkaBoneAttachment;

#define hkaiNavMeshClearanceCache__McpDataInteger_HASH 0x89AC06B2
typedef struct hkaiNavMeshClearanceCache__McpDataInteger {
    hkUint8 interpolant; // offset: 0, flags: 32, size: 0
    hkUint8 clearance; // offset: 1, flags: 32, size: 0
} hkaiNavMeshClearanceCache__McpDataInteger;

#define hkRefPtr_hkaSkeleton_HASH 0x8B00BDD7
typedef struct hkRefPtr_hkaSkeleton {
    hkaSkeleton* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaSkeleton;

#define hkcdStaticAabbTree_HASH 0x8CC6A613
typedef struct hkcdStaticAabbTree {
    struct hkReferencedObject;
    hkBool shouldDeleteTree; // offset: 24, flags: 33, size: 1
    hkcdStaticAabbTree__Impl* treePtr; // offset: 32, flags: 34, size: 8
} hkcdStaticAabbTree;

#define hkPtrAndInt_hkPropertyDesc_unsigned_int_1_HASH 0xF6D5C69F
typedef struct hkPtrAndInt_hkPropertyDesc_unsigned_int_1 {
    hkPropertyDesc* ptrAndInt; // offset: 0, flags: 36, size: 8
} hkPtrAndInt_hkPropertyDesc_unsigned_int_1;

#define hkPropertyId_HASH 0xE8A9A57F
typedef struct hkPropertyId {
    hkPtrAndInt_hkPropertyDesc_unsigned_int_1 desc; // offset: 0, flags: 37, size: 8
} hkPropertyId;

#define hkReflect__QualifiedType_hkReflect__Type_HASH 0xB7321059
typedef struct hkReflect__QualifiedType_hkReflect__Type {
    hkReflect__Type* type; // offset: 0, flags: 36, size: 8
} hkReflect__QualifiedType_hkReflect__Type;

#define hkReflect__Any_HASH 0xE1104999
typedef struct hkReflect__Any {
    hkReflect__QualifiedType_hkReflect__Type type; // offset: 0, flags: 36, size: 8
    unsigned_char status; // offset: 8, flags: 36, size: 1
    hkUintReal buf[4]; // offset: 16, flags: 36, size: 16
} hkReflect__Any;

#define hkTuple_hkPropertyId_hkReflect__Any_void_void_void_void_void_void_HASH 0x919E7D19
typedef struct hkTuple_hkPropertyId_hkReflect__Any_void_void_void_void_void_void {
    hkPropertyId _0; // offset: 0, flags: 32, size: 8
    hkReflect__Any _1; // offset: 16, flags: 32, size: 32
} hkTuple_hkPropertyId_hkReflect__Any_void_void_void_void_void_void;

#define hkRefPtr_hkLocalFrame_HASH 0x94C3BB5F
typedef struct hkRefPtr_hkLocalFrame {
    hkLocalFrame* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkLocalFrame;

#define hkaiDirectedGraphExplicitCost__Node_HASH 0x954456FC
typedef struct hkaiDirectedGraphExplicitCost__Node {
    int startEdgeIndex; // offset: 0, flags: 32, size: 4
    int numEdges; // offset: 4, flags: 32, size: 4
} hkaiDirectedGraphExplicitCost__Node;

#define hkaSkeleton__LocalFrameOnBone_HASH 0x95C04023
typedef struct hkaSkeleton__LocalFrameOnBone {
    hkRefPtr_hkLocalFrame localFrame; // offset: 0, flags: 32, size: 8
    hkInt16 boneIndex; // offset: 8, flags: 32, size: 0
} hkaSkeleton__LocalFrameOnBone;

#define hkEnum_hkxIndexBuffer__IndexType_hkInt8_HASH 0x98819BCB
typedef enum hkEnum_hkxIndexBuffer__IndexType_hkInt8 { // size: 0
} hkEnum_hkxIndexBuffer__IndexType_hkInt8;

#define hkPropertyDesc_HASH 0x9BB7B519
typedef struct hkPropertyDesc {
    hkReflect__Type* type; // offset: 0, flags: 32, size: 8
    const_char* name; // offset: 8, flags: 32, size: 8
    hkFlags_hkPropertyFlags__Enum_hkUint32 flags; // offset: 16, flags: 32, size: 0
} hkPropertyDesc;

#define hkArray_hkaBone_hkContainerHeapAllocator_HASH 0xB238B5B4
typedef struct hkArray_hkaBone_hkContainerHeapAllocator {
    hkaBone* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaBone_hkContainerHeapAllocator;

#define hkArray_hkQsTransform_hkContainerHeapAllocator_HASH 0xB8D605DF
typedef struct hkArray_hkQsTransform_hkContainerHeapAllocator {
    hkQsTransform* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkQsTransform_hkContainerHeapAllocator;

#define hkArray_hkReal_hkContainerHeapAllocator_HASH 0xE84876EB
typedef struct hkArray_hkReal_hkContainerHeapAllocator {
    hkReal* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkReal_hkContainerHeapAllocator;

#define hkaSkeleton_HASH 0xA0349615
typedef struct hkaSkeleton {
    struct hkReferencedObject;
    hkStringPtr name; // offset: 24, flags: 32, size: 8
    hkArray_hkInt16_hkContainerHeapAllocator parentIndices; // offset: 32, flags: 32, size: 16
    hkArray_hkaBone_hkContainerHeapAllocator bones; // offset: 48, flags: 32, size: 16
    hkArray_hkQsTransform_hkContainerHeapAllocator referencePose; // offset: 64, flags: 32, size: 16
    hkArray_hkReal_hkContainerHeapAllocator referenceFloats; // offset: 80, flags: 32, size: 16
    hkArray_hkStringPtr_hkContainerHeapAllocator floatSlots; // offset: 96, flags: 32, size: 16
    hkArray_hkaSkeleton__LocalFrameOnBone_hkContainerHeapAllocator localFrames; // offset: 112, flags: 32, size: 16
    hkArray_hkaSkeleton__Partition_hkContainerHeapAllocator partitions; // offset: 128, flags: 32, size: 16
} hkaSkeleton;

#define hkxMesh__UserChannelInfo_HASH 0xA67A10AF
typedef struct hkxMesh__UserChannelInfo {
    struct hkxAttributeHolder;
    hkStringPtr name; // offset: 40, flags: 32, size: 8
    hkStringPtr className; // offset: 48, flags: 32, size: 8
} hkxMesh__UserChannelInfo;

#define hkxVertexAnimation_HASH 0xAB77D77B
typedef struct hkxVertexAnimation {
    struct hkReferencedObject;
    hkReal time; // offset: 24, flags: 32, size: 0
    hkxVertexBuffer vertData; // offset: 32, flags: 32, size: 144
    hkArray_hkInt32_hkContainerHeapAllocator vertexIndexMap; // offset: 176, flags: 32, size: 16
    hkArray_hkxVertexAnimation__UsageMap_hkContainerHeapAllocator componentMap; // offset: 192, flags: 32, size: 16
} hkxVertexAnimation;

#define hkQsTransformf_HASH 0xAD660A82
typedef struct hkQsTransformf {
    hkVector4f translation; // offset: 0, flags: 32, size: 16
    hkQuaternionf rotation; // offset: 16, flags: 32, size: 16
    hkVector4f scale; // offset: 32, flags: 32, size: 16
} hkQsTransformf;

#define hkHalf16_HASH 0xFF22E787
typedef struct hkHalf16 {
    hkInt16 value; // offset: 0, flags: 36, size: 0
} hkHalf16;

#define hkaiNavMesh__Edge_HASH 0xB3347C86
typedef struct hkaiNavMesh__Edge {
    hkaiIndex_hkInt32 a; // offset: 0, flags: 32, size: 0
    hkaiIndex_hkInt32 b; // offset: 4, flags: 32, size: 0
    hkaiPackedKey__hkaiIndex_hkaiIndex oppositeEdge; // offset: 8, flags: 32, size: 0
    hkaiPackedKey__hkaiIndex_hkaiIndex oppositeFace; // offset: 12, flags: 32, size: 0
    hkFlags_hkaiNavMesh__EdgeFlagBits_hkUint8 flags; // offset: 16, flags: 32, size: 0
    hkUint8 paddingByte; // offset: 17, flags: 33, size: 0
    hkHalf16 userEdgeCost; // offset: 18, flags: 32, size: 2
} hkaiNavMesh__Edge;

#define hkxIndexBuffer_HASH 0xB4A2D44D
typedef struct hkxIndexBuffer {
    struct hkReferencedObject;
    hkEnum_hkxIndexBuffer__IndexType_hkInt8 indexType; // offset: 24, flags: 32, size: 0
    hkArray_hkUint16_hkContainerHeapAllocator indices16; // offset: 32, flags: 32, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator indices32; // offset: 48, flags: 32, size: 16
    hkUint32 vertexBaseOffset; // offset: 64, flags: 32, size: 0
    hkUint32 length; // offset: 68, flags: 32, size: 0
} hkxIndexBuffer;

#define hkaiStreamingSet__GraphConnection_HASH 0xB4A9069D
typedef struct hkaiStreamingSet__GraphConnection {
    int aNodeIndex; // offset: 0, flags: 32, size: 4
    int bNodeIndex; // offset: 4, flags: 32, size: 4
    hkUint32 aEdgeData; // offset: 8, flags: 32, size: 0
    hkUint32 bEdgeData; // offset: 12, flags: 32, size: 0
    hkHalf16 aEdgeCost; // offset: 16, flags: 32, size: 2
    hkHalf16 bEdgeCost; // offset: 18, flags: 32, size: 2
} hkaiStreamingSet__GraphConnection;

#define hkxAttribute_HASH 0xB7327AB7
typedef struct hkxAttribute {
    hkStringPtr name; // offset: 0, flags: 32, size: 8
    hkRefVariant value; // offset: 8, flags: 32, size: 8
} hkxAttribute;

#define hkArray_hkxAttribute_hkContainerHeapAllocator_HASH 0xE2F1C136
typedef struct hkArray_hkxAttribute_hkContainerHeapAllocator {
    hkxAttribute* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkxAttribute_hkContainerHeapAllocator;

#define hkxAttributeGroup_HASH 0xB77C4E21
typedef struct hkxAttributeGroup {
    hkStringPtr name; // offset: 0, flags: 32, size: 8
    hkArray_hkxAttribute_hkContainerHeapAllocator attributes; // offset: 8, flags: 32, size: 16
} hkxAttributeGroup;

#define hkaiDirectedGraphExplicitCost_HASH 0xB7E33436
typedef struct hkaiDirectedGraphExplicitCost {
    struct hkReferencedObject;
    hkArray_hkVector4_hkContainerHeapAllocator positions; // offset: 24, flags: 32, size: 16
    hkArray_hkaiDirectedGraphExplicitCost__Node_hkContainerHeapAllocator nodes; // offset: 40, flags: 32, size: 16
    hkArray_hkaiDirectedGraphExplicitCost__Edge_hkContainerHeapAllocator edges; // offset: 56, flags: 32, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator nodeData; // offset: 72, flags: 32, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator edgeData; // offset: 88, flags: 32, size: 16
    int nodeDataStriding; // offset: 104, flags: 32, size: 4
    int edgeDataStriding; // offset: 108, flags: 32, size: 4
    hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator streamingSets; // offset: 112, flags: 32, size: 16
} hkaiDirectedGraphExplicitCost;

#define hkArray_hkaMeshBinding__Mapping_hkContainerHeapAllocator_HASH 0xBABC52BE
typedef struct hkArray_hkaMeshBinding__Mapping_hkContainerHeapAllocator {
    hkaMeshBinding__Mapping* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaMeshBinding__Mapping_hkContainerHeapAllocator;

#define hkEnum_hkaiAnnotatedStreamingSet__Side_hkUint8_HASH 0xBBA05363
typedef enum hkEnum_hkaiAnnotatedStreamingSet__Side_hkUint8 { // size: 0
} hkEnum_hkaiAnnotatedStreamingSet__Side_hkUint8;

#define hkaAnimationBinding_HASH 0xBCBFCA8E
typedef struct hkaAnimationBinding {
    struct hkReferencedObject;
    hkStringPtr originalSkeletonName; // offset: 24, flags: 32, size: 8
    hkRefPtr_hkaAnimation animation; // offset: 32, flags: 32, size: 8
    hkArray_hkInt16_hkContainerHeapAllocator transformTrackToBoneIndices; // offset: 40, flags: 32, size: 16
    hkArray_hkInt16_hkContainerHeapAllocator floatTrackToFloatSlotIndices; // offset: 56, flags: 32, size: 16
    hkArray_hkInt16_hkContainerHeapAllocator partitionIndices; // offset: 72, flags: 32, size: 16
    hkEnum_hkaAnimationBinding__BlendHint_hkInt8 blendHint; // offset: 88, flags: 32, size: 0
} hkaAnimationBinding;

#define hkArray_hkaiNavMesh__Face_hkContainerHeapAllocator_HASH 0xF86E63B6
typedef struct hkArray_hkaiNavMesh__Face_hkContainerHeapAllocator {
    hkaiNavMesh__Face* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkaiNavMesh__Face_hkContainerHeapAllocator;

#define hkRefPtr_hkaiNavMeshClearanceCacheSeeding__CacheDataSet_HASH 0xFED96CAB
typedef struct hkRefPtr_hkaiNavMeshClearanceCacheSeeding__CacheDataSet {
    hkaiNavMeshClearanceCacheSeeding__CacheDataSet* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaiNavMeshClearanceCacheSeeding__CacheDataSet;

#define hkaiNavMesh_HASH 0xBCF7C531
typedef struct hkaiNavMesh {
    struct hkReferencedObject;
    hkArray_hkaiNavMesh__Face_hkContainerHeapAllocator faces; // offset: 24, flags: 32, size: 16
    hkArray_hkaiNavMesh__Edge_hkContainerHeapAllocator edges; // offset: 40, flags: 32, size: 16
    hkArray_hkVector4_hkContainerHeapAllocator vertices; // offset: 56, flags: 32, size: 16
    hkArray_hkaiAnnotatedStreamingSet_hkContainerHeapAllocator streamingSets; // offset: 72, flags: 32, size: 16
    hkArray_hkInt32_hkContainerHeapAllocator faceData; // offset: 88, flags: 32, size: 16
    hkArray_hkInt32_hkContainerHeapAllocator edgeData; // offset: 104, flags: 32, size: 16
    int faceDataStriding; // offset: 120, flags: 32, size: 4
    int edgeDataStriding; // offset: 124, flags: 32, size: 4
    unsigned_char flags; // offset: 128, flags: 36, size: 1
    hkAabb aabb; // offset: 144, flags: 32, size: 32
    hkReal erosionRadius; // offset: 176, flags: 32, size: 0
    hkUlong userData; // offset: 184, flags: 32, size: 0
    hkRefPtr_hkaiNavMeshClearanceCacheSeeding__CacheDataSet clearanceCacheSeedingDataSet; // offset: 192, flags: 32, size: 8
} hkaiNavMesh;

#define hkArray_hkTransform_hkContainerHeapAllocator_HASH 0xF9390889
typedef struct hkArray_hkTransform_hkContainerHeapAllocator {
    hkTransform* m_data; // offset: 0, flags: 34, size: 8
    int m_size; // offset: 8, flags: 34, size: 4
    int m_capacityAndFlags; // offset: 12, flags: 34, size: 4
} hkArray_hkTransform_hkContainerHeapAllocator;

#define hkaMeshBinding_HASH 0xC0550816
typedef struct hkaMeshBinding {
    struct hkReferencedObject;
    hkRefPtr_hkxMesh mesh; // offset: 24, flags: 32, size: 8
    hkStringPtr originalSkeletonName; // offset: 32, flags: 32, size: 8
    hkStringPtr name; // offset: 40, flags: 32, size: 8
    hkRefPtr_hkaSkeleton skeleton; // offset: 48, flags: 32, size: 8
    hkArray_hkaMeshBinding__Mapping_hkContainerHeapAllocator mappings; // offset: 56, flags: 32, size: 16
    hkArray_hkTransform_hkContainerHeapAllocator boneFromSkinMeshTransforms; // offset: 72, flags: 32, size: 16
} hkaMeshBinding;

#define hkaiDirectedGraphExplicitCost__Edge_HASH 0xC3134F91
typedef struct hkaiDirectedGraphExplicitCost__Edge {
    hkHalf16 cost; // offset: 0, flags: 32, size: 2
    hkFlags_hkaiDirectedGraphExplicitCost__EdgeBits_hkUint16 flags; // offset: 2, flags: 32, size: 0
    hkaiPackedKey__hkaiIndex_hkaiIndex target; // offset: 4, flags: 34, size: 0
} hkaiDirectedGraphExplicitCost__Edge;

#define hkMeshBoneIndexMapping_HASH 0xC386E975
typedef struct hkMeshBoneIndexMapping {
    hkArray_hkInt16_hkContainerHeapAllocator mapping; // offset: 0, flags: 32, size: 16
} hkMeshBoneIndexMapping;

#define hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum_HASH 0xC3F6A72B
typedef enum hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum { // size: 4
} hkaAnimatedReferenceFrame__hkaReferenceFrameTypeEnum;

#define hkaiAnnotatedStreamingSet_HASH 0xC93646DD
typedef struct hkaiAnnotatedStreamingSet {
    hkEnum_hkaiAnnotatedStreamingSet__Side_hkUint8 side; // offset: 0, flags: 32, size: 0
    hkRefPtr_hkaiStreamingSet streamingSet; // offset: 8, flags: 32, size: 8
} hkaiAnnotatedStreamingSet;

#define hkRefPtr_hkaAnimationBinding_HASH 0xC9D52541
typedef struct hkRefPtr_hkaAnimationBinding {
    hkaAnimationBinding* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkaAnimationBinding;

#define hkxIndexBuffer__IndexType_HASH 0xCA5D1A1C
typedef enum hkxIndexBuffer__IndexType { // size: 4
} hkxIndexBuffer__IndexType;

#define hkxMaterial__TextureStage_HASH 0xCBB9F29B
typedef struct hkxMaterial__TextureStage {
    hkRefVariant texture; // offset: 0, flags: 32, size: 8
    hkEnum_hkxMaterial__TextureType_hkInt32 usageHint; // offset: 8, flags: 32, size: 0
    hkInt32 tcoordChannel; // offset: 12, flags: 32, size: 0
} hkxMaterial__TextureStage;

/* primitive unsigned char*/
#define hkRefPtr_hkxMesh__UserChannelInfo_HASH 0xCDD37839
typedef struct hkRefPtr_hkxMesh__UserChannelInfo {
    hkxMesh__UserChannelInfo* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxMesh__UserChannelInfo;

#define hkxMaterial__UVMappingAlgorithm_HASH 0xCE00C132
typedef enum hkxMaterial__UVMappingAlgorithm { // size: 4
} hkxMaterial__UVMappingAlgorithm;

#define hkaAnimationContainer_HASH 0xD017E2F4
typedef struct hkaAnimationContainer {
    struct hkReferencedObject;
    hkArray_hkRefPtr_hkContainerHeapAllocator skeletons; // offset: 24, flags: 32, size: 16
    hkArray_hkRefPtr_hkContainerHeapAllocator animations; // offset: 40, flags: 32, size: 16
    hkArray_hkRefPtr_hkContainerHeapAllocator bindings; // offset: 56, flags: 32, size: 16
    hkArray_hkRefPtr_hkContainerHeapAllocator attachments; // offset: 72, flags: 32, size: 16
    hkArray_hkRefPtr_hkContainerHeapAllocator skins; // offset: 88, flags: 32, size: 16
} hkaAnimationContainer;

#define hkDefaultPropertyBag_HASH 0xD3707717
typedef struct hkDefaultPropertyBag {
    hkHashMap_hkPropertyId_hkReflect__Any propertyMap; // offset: 0, flags: 34, size: 32
    hkHashMap_hkPropertyId_hkReflect__Any transientPropertyMap; // offset: 32, flags: 35, size: 32
} hkDefaultPropertyBag;

#define hkTransformf_HASH 0xD3AA90B5
typedef struct hkTransformf {
    hkRotationf rotation; // offset: 0, flags: 34, size: 0
    hkVector4f translation; // offset: 48, flags: 34, size: 16
} hkTransformf;

#define hkaSplineCompressedAnimation_HASH 0xD640A594
typedef struct hkaSplineCompressedAnimation {
    struct hkaAnimation;
    int numFrames; // offset: 64, flags: 36, size: 4
    int numBlocks; // offset: 68, flags: 36, size: 4
    int maxFramesPerBlock; // offset: 72, flags: 36, size: 4
    int maskAndQuantizationSize; // offset: 76, flags: 36, size: 4
    hkReal blockDuration; // offset: 80, flags: 36, size: 0
    hkReal blockInverseDuration; // offset: 84, flags: 36, size: 0
    hkReal frameDuration; // offset: 88, flags: 36, size: 0
    hkArray_hkUint32_hkContainerHeapAllocator blockOffsets; // offset: 96, flags: 36, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator floatBlockOffsets; // offset: 112, flags: 36, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator transformOffsets; // offset: 128, flags: 36, size: 16
    hkArray_hkUint32_hkContainerHeapAllocator floatOffsets; // offset: 144, flags: 36, size: 16
    hkArray_hkUint8_hkContainerHeapAllocator data; // offset: 160, flags: 36, size: 16
    int endian; // offset: 176, flags: 36, size: 4
} hkaSplineCompressedAnimation;

#define hkaiNavMesh__Face_HASH 0xDAF49E0E
typedef struct hkaiNavMesh__Face {
    hkaiIndex_hkInt32 startEdgeIndex; // offset: 0, flags: 32, size: 0
    hkaiIndex_hkInt32 startUserEdgeIndex; // offset: 4, flags: 32, size: 0
    hkInt16 numEdges; // offset: 8, flags: 32, size: 0
    hkInt16 numUserEdges; // offset: 10, flags: 32, size: 0
    hkInt16 clusterIndex; // offset: 12, flags: 32, size: 0
    hkUint16 padding; // offset: 14, flags: 32, size: 0
} hkaiNavMesh__Face;

#define hkxVertexDescription__ElementDecl_HASH 0xDD0D0CA5
typedef struct hkxVertexDescription__ElementDecl {
    hkUint32 byteOffset; // offset: 0, flags: 32, size: 0
    hkEnum_hkxVertexDescription__DataType_hkUint16 type; // offset: 4, flags: 32, size: 0
    hkEnum_hkxVertexDescription__DataUsage_hkUint16 usage; // offset: 6, flags: 32, size: 0
    hkUint32 byteStride; // offset: 8, flags: 32, size: 0
    hkUint8 numElements; // offset: 12, flags: 32, size: 0
    hkStringPtr channelID; // offset: 16, flags: 32, size: 8
} hkxVertexDescription__ElementDecl;

/* primitive unsigned long long*/
#define hkaiStreamingSet__VolumeConnection_HASH 0xE41E4B36
typedef struct hkaiStreamingSet__VolumeConnection {
    hkaiIndex_hkInt32 aCellIndex; // offset: 0, flags: 32, size: 0
    hkaiIndex_hkInt32 bCellIndex; // offset: 4, flags: 32, size: 0
} hkaiStreamingSet__VolumeConnection;

#define hkaiAnnotatedStreamingSet__Side_HASH 0xE6E0651A
typedef enum hkaiAnnotatedStreamingSet__Side { // size: 4
} hkaiAnnotatedStreamingSet__Side;

#define hkRefPtr_hkxIndexBuffer_HASH 0xE7F89D01
typedef struct hkRefPtr_hkxIndexBuffer {
    hkxIndexBuffer* ptr; // offset: 0, flags: 36, size: 8
} hkRefPtr_hkxIndexBuffer;

/* primitive HavokVector4*/
#define hkxMaterial__Property_HASH 0xFFA5F2DB
typedef struct hkxMaterial__Property {
    hkUint32 key; // offset: 0, flags: 32, size: 0
    hkUint32 value; // offset: 4, flags: 32, size: 0
} hkxMaterial__Property;

#endif //HAVOK_TYPES_GUARD
